apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cassandra
  name: cassandra
spec:
  containers:
  - image: cassandra
    imagePullPolicy: IfNotPresent
    name: cassandra
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
