apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
  labels:
    type: nfspv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
   path: /opt/sfw
   server: 172.31.31.2
   readOnly: false
