apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv1
  labels:
    type: nfspv1
spec:
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
   path: /opt/sfw
   server: 172.31.31.2
   readOnly: false
