apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginxservice
  name: nginxservice
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: ClusterIP
status:
  loadBalancer: {}
