apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvwithhostpath
  labels:
    type: pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
