apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvchost
  labels:
    type: pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
