apiVersion: v1
kind: Pod
metadata:
  name: secretasvolume
spec:
  containers:
  - name: shell
    image: busybox
    command:
    - "sh"
    - "-c"
    - "sleep 10000"
    volumeMounts:
    - name: secret
      mountPath: "/tmp/access"
  volumes:
  - name: secret
    secret:
      secretName: pp
