apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginxwedir
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    ports:
    - containerPort: 80
    volumeMounts:
    - name: emptydir
      mountPath: /opt
  volumes:
  - name: emptydir
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
