apiVersion: v1
kind: Pod
metadata:
  name: podswithcm
spec:
  containers:
  - name: podswithcm
    image: centos:7
    command:
    - "bin/bash"
    - "-c"
    - "sleep 10000"
    ports:
    - containerPort: 80
    env:
    - name: hello
      valueFrom:
       configMapKeyRef:
         name: hello
