apiVersion: v1
kind: Pod
metadata:
  name: volwithcm
spec:
  containers:
  - name: volwithcm
    image: centos:7
    command:
    - "bin/bash"
    - "-c"
    - "sleep 10000"
    volumeMounts:
    - name: volwithcm
      mountPath: /etc/config
  volumes:
  - name: volwithcm
    configMap:
      name: hello
